"""add_users_table_and_formula_review_fields

Revision ID: 6952250ffe51
Revises: fbbaa31bbf2d
Create Date: 2026-03-08 00:49:55.013687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6952250ffe51'
down_revision: Union[str, None] = 'fbbaa31bbf2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('username', sa.String(length=50), nullable=False),
        sa.Column('password_hash', sa.String(length=255), nullable=False),
        sa.Column('display_name', sa.String(length=100), nullable=True),
        sa.Column('role', sa.String(length=20), nullable=False, server_default='user'),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default='1'),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.add_column('formulas', sa.Column('status', sa.String(length=20), server_default='draft', nullable=False))
    op.add_column('formulas', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('formulas', sa.Column('reviewed_by', sa.Integer(), nullable=True))
    op.add_column('formulas', sa.Column('reviewed_at', sa.DateTime(), nullable=True))
    op.add_column('formulas', sa.Column('review_comment', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'formulas', 'users', ['reviewed_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'formulas', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'formulas', type_='foreignkey')
    op.drop_constraint(None, 'formulas', type_='foreignkey')
    op.drop_column('formulas', 'review_comment')
    op.drop_column('formulas', 'reviewed_at')
    op.drop_column('formulas', 'reviewed_by')
    op.drop_column('formulas', 'created_by')
    op.drop_column('formulas', 'status')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
