"""drop_ast_data_column

Revision ID: 69e070b69cba
Revises: d5c0b7dbe935
Create Date: 2026-03-08 22:06:11.071233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '69e070b69cba'
down_revision: Union[str, None] = 'd5c0b7dbe935'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('formulas', 'ast_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('formulas', sa.Column('ast_data', mysql.JSON(), nullable=False))
    # ### end Alembic commands ###
