"""add_abbreviation_to_formulas

Revision ID: d5c0b7dbe935
Revises: 6952250ffe51
Create Date: 2026-03-08 20:55:32.558137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5c0b7dbe935'
down_revision: Union[str, None] = '6952250ffe51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('formulas', sa.Column('abbreviation', sa.String(length=50), nullable=True, comment='公式縮寫'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('formulas', 'abbreviation')
    # ### end Alembic commands ###
