"""add_is_active_to_departments_and_formulas

Revision ID: fbbaa31bbf2d
Revises: 
Create Date: 2026-03-08 00:26:29.935525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbbaa31bbf2d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False))
    op.add_column('formulas', sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('formulas', 'is_active')
    op.drop_column('departments', 'is_active')
    # ### end Alembic commands ###
